hgserver: filter Apache internal dummy connection from access log tests. r=sheehan,shtrom
Apache emits an "OPTIONS * HTTP/1.0 ... (internal dummy connection)"
log line when it spins up worker processes. This is nondeterministic
and unrelated to what these tests assert, so it intermittently slips
into the access log and breaks the exact-match comparison, e.g.:

> --- /app/vct/hgserver/tests/test-push-basic.t
> +++ /app/vct/hgserver/tests/test-push-basic.t.err
> @@ -217,6 +217,7 @@
>    * - - [*/*/*:*:*:* +0000] "POST /mozilla-central?cmd=listkeys HTTP/1.1" 200 * "-" "mercurial/proto-1.0 (Mercurial *)" (glob)
>    * - - [*/*/*:*:*:* +0000] "POST /mozilla-central?cmd=listkeys HTTP/1.1" 200 - "-" "mercurial/proto-1.0 (Mercurial *)" (glob)
>    * - - [*/*/*:*:*:* +0000] "POST /mozilla-central?cmd=unbundle HTTP/1.1" 401 * "-" "mercurial/proto-1.0 (Mercurial *)" (glob)
> +  $LOCALIP - - [11/Jun/2026:08:38:19 +0000] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.62 (Rocky Linux) mod_wsgi/4.7.1 Python/3.9 (internal dummy connection)"
>    * - - [*/*/*:*:*:* +0000] "GET /mozilla-central/json-rev/77538e1ce4be HTTP/1.1" 200 * "-" "-" (glob)
>    * - - [*/*/*:*:*:* +0000] "GET /mozilla-central/json-pushes HTTP/1.1" 200 * "-" "-" (glob)
>    $ hgmo exec hgweb0 cat /var/log/httpd/hg.mozilla.org/error_log
>
> ERROR: test-push-basic.t output changed

Pipe the access_log through grep -v to drop it.

Differential Revision: https://phabricator.services.mozilla.com/D306091