vcsreplicator: update test-delete.t to accept output from newer coreutils r=sheehan
Fixes this failure when moving from centos:7 to rockylinux:8:

```
--- /app/vct/pylib/vcsreplicator/tests/test-delete.t
+++ /app/vct/pylib/vcsreplicator/tests/test-delete.t.err
@@ -59,13 +59,13 @@
 Confirm the repos are deleted

   $ hgmo exec hgssh ls -la /repo/hg/mozilla/mozilla-central
-  ls: cannot access /repo/hg/mozilla/mozilla-central: No such file or directory
+  ls: cannot access '/repo/hg/mozilla/mozilla-central': No such file or directory
   [2]
   $ hgmo exec hgweb0 ls -la /repo/hg/mozilla/mozilla-central
-  ls: cannot access /repo/hg/mozilla/mozilla-central: No such file or directory
+  ls: cannot access '/repo/hg/mozilla/mozilla-central': No such file or directory
   [2]
   $ hgmo exec hgweb1 ls -la /repo/hg/mozilla/mozilla-central
-  ls: cannot access /repo/hg/mozilla/mozilla-central: No such file or directory
+  ls: cannot access '/repo/hg/mozilla/mozilla-central': No such file or directory
   [2]

 Set `consumer.backup=true` on a node and re-create the repos to test deletion on a backup node

ERROR: test-delete.t output changed
```

Differential Revision: https://phabricator.services.mozilla.com/D212659

--HG--
extra : moz-landing-system : lando