hooks: fix test-single_head_per_branch.t. r=sheehan
Something seems to have changed that causes mercurial to consider we're
pushing a new head, so force-push to restore previous behavior.

```
--- /app/vct/hghooks/tests/test-single_head_per_branch.t
+++ /app/vct/hghooks/tests/test-single_head_per_branch.t.err
@@ -149,9 +149,8 @@
   $ hg push
   pushing to $TESTTMP/mozilla-central
   searching for changes
-  adding changesets
-  adding manifests
-  adding file changes
-  added 1 changesets with 1 changes to 1 files
+  abort: push creates new remote head 6e5ba34a14d0
+  (merge or see 'hg help push' for details about pushing new heads)
+  [255]

   $ cd ..

ERROR: test-single_head_per_branch.t output changed
```

Differential Revision: https://phabricator.services.mozilla.com/D211546

--HG--
extra : moz-landing-system : lando