scripts: use copy_from instead of copy; r=sheehan
After the upgrade to boto3, copies in production started
failing with the following:

   botocore.exceptions.ClientError: An error occurred (InvalidRequest)
   when calling the CopyObject operation: This copy request is illegal
   because it is trying to copy an object to itself without changing
   the object's metadata, storage class, website redirect location or
   encryption attributes.

While untested, I'm optimistic this variation of copying will
fix the problem. (I believe copy_from() uses remote copy
whereas copy() uses a different copying methodology where the
smarts are implemented locally instead of remotely.)

Differential Revision: https://phabricator.services.mozilla.com/D2363

--HG--
extra : moz-landing-system : lando