robustcheckout: silence warnings in test-locks (bug 1897982) r=sheehan
Not releasing the lock caused deprecation warnings from __del__:
```
--- /app/vct/hgext/robustcheckout/tests/test-locks.t
+++ /app/vct/hgext/robustcheckout/tests/test-locks.t.err
@@ -35,6 +35,8 @@
 directory update.

   $ hg -R wdirlock acquirewlock
+  /app/venv/lib/python3.7/site-packages/mercurial/util.py:1881: DeprecationWarning: use lock.release instead of del lock
+    return func(*args, **kwargs)
   $ readlink wdirlock/.hg/wlock
   dummyhost:* (glob)

@@ -63,6 +65,8 @@
   $ cd ../..

   $ hg -R wdirlock-pull acquirewlock
+  /app/venv/lib/python3.7/site-packages/mercurial/util.py:1881: DeprecationWarning: use lock.release instead of del lock
+    return func(*args, **kwargs)
   $ readlink wdirlock-pull/.hg/wlock
   dummyhost:* (glob)

@@ -90,6 +94,8 @@
   ensuring http://$LOCALHOST:$HGPORT/repo1@7d5b54cb09e1 is available at storelock
   updated to 7d5b54cb09e1172a3684402520112cab3f3a1b70
   $ hg -R storelock acquirestorelock
+  /app/venv/lib/python3.7/site-packages/mercurial/util.py:1881: DeprecationWarning: use lock.release instead of del lock
+    return func(*args, **kwargs)
   $ readlink share/65cd4e3b46a3f22a08ec4162871e67f57c322f6a/.hg/store/lock
   dummyhost:* (glob)

@@ -119,6 +125,8 @@
   ensuring http://$LOCALHOST:$HGPORT/repo1@7d5b54cb09e1 is available at storelock-pull
   updated to 7d5b54cb09e1172a3684402520112cab3f3a1b70
   $ hg -R storelock-pull acquirestorelock
+  /app/venv/lib/python3.7/site-packages/mercurial/util.py:1881: DeprecationWarning: use lock.release instead of del lock
+    return func(*args, **kwargs)
   $ readlink share/65cd4e3b46a3f22a08ec4162871e67f57c322f6a/.hg/store/lock
   dummyhost:* (glob)

@@ -145,6 +153,8 @@
 Simulate a held lock on the store without a working directory

   $ hg -R storelock acquirestorelock
+  /app/venv/lib/python3.7/site-packages/mercurial/util.py:1881: DeprecationWarning: use lock.release instead of del lock
+    return func(*args, **kwargs)
   $ readlink share/65cd4e3b46a3f22a08ec4162871e67f57c322f6a/.hg/store/lock
   dummyhost:* (glob)


ERROR: test-locks.t output changed
```

Differential Revision: https://phabricator.services.mozilla.com/D211038

--HG--
extra : moz-landing-system : lando