hgmo: fix fastannotate TypeError. r=sheehan
This was causing truncated responses from hgweb, and errors in httpd logs, e.g.
when running hgserver/tests/test-fastannotate.t:

```
Traceback (most recent call last):
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/hgweb/hgwebdir_mod.py", line 385, in run_wsgi
    for r in self._runwsgi(req, res):
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/hgweb/hgweb_mod.py", line 365, in run_wsgi
    for r in self._runwsgi(req, res, repo):
  File "/var/hg/version-control-tools/hgext/serverlog/__init__.py", line 423, in wrapped_runwsgi
    for what in orig(self, req, res, repo):
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/hgweb/request.py", line 581, in sendresponse
    for chunk in self._bodygen:
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/util.py", line 1791, in increasingchunks
    for chunk in source:
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/templateutil.py", line 874, in flatten
    for j in flatten(context, mapping, i):
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/templateutil.py", line 864, in flatten
    for i in thing:
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/templateutil.py", line 1161, in joinitems
    for x in itemiter:
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/templateutil.py", line 1111, in _applymap
    for lm in _iteroverlaymaps(context, mapping, diter):
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/templateutil.py", line 1096, in _iteroverlaymaps
    for i, nm in enumerate(newmappings):
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/hgweb/webcommands.py", line 1020, in annotate
    lines = webutil.annotate(web.req, fctx, web.repo.ui)
  File "/var/hg/version-control-tools/hgext/hgmo/__init__.py", line 888, in hgwebfastannotate
    diffopts = webutil.difffeatureopts(req, ui, "annotate")
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/hgweb/webutil.py", line 230, in difffeatureopts
    ui, untrusted=True, section=section, whitespace=True
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/diffutil.py", line 96, in difffeatureopts
    b'nodates': get(b'nodates'),
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/diffutil.py", line 91, in get
    section, configprefix + (name or key), untrusted=untrusted
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/ui.py", line 793, in configbool
    v = self._config(section, name, default, untrusted=untrusted)
  File "/var/hg/venv_hgweb/lib64/python3.6/site-packages/mercurial/ui.py", line 670, in _config
    msg %= (section, name)
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
```

Differential Revision: https://phabricator.services.mozilla.com/D212427

--HG--
extra : moz-landing-system : lando